eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
#ribbon:
    #eureka:
       #enabled: false  #配置zuul路由时 将此属性设置为false

#service-my:
  #ribbon:
    #listOfServers: http://local:8762

#service-you:
  #ribbon:
    #listOfServers: http://local:8765


