eureka:
  client:
    service-url-defaultZone: http://localhost:8761/eureka/
server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/CQHaveADream/myCloudConfig
          username: CQHaveADream
          password: hahaheihei123
          search-paths: config-repo




